### ISSUE TITLE
Chord bot ?

### ISSUE THREAD

**Issue by moonsh** [Palash90/chordMelody#1]
Thank you for sharing your work.

I wonder what chorbot you are using.
Could you share your chordbot or could you recommend any chordbot ?

**Comment by Palash90** [comment]
Chordbot is an android and iPhone app.

On the paid version of the app, you can upload a json file and it generates midi file and wav file. The generated midi file or wav file can be used as the backing track and you can use the program generated melody and complete a song.

**Comment by Palash90** [comment]
Closed with answer.

**Comment by moonsh** [comment]
@Palash90 I see. Thank you. One more question. So when I create a midi file, it's just one track melody sound. To add accompaniment, I need the chord bot, correct?

**Comment by Palash90** [comment]
Yes, for the accompaniment, you need the Chordbot.
